name: depoly
on:
  push:
    only:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: masarakki/docker-alias@v1
        with:
          image: vvakame/review:3.2
          commands: 'review-pdfmaker'
      - uses: action/setup-ruby@v1
        with:
          ruby_version: 2.7
      - run: bundle install -j4 --path vendor/bundle
      - run: bundle exec rake review_files
      - run: review-pdfmaker config.yml
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - run: aws s3 cp book.pdf s3://np-complete-books/pdf/C97.pdf --acl public-read
